# Generated by Django 5.2.17 on 2026-09-24 02:55

import django.db.models.deletion
import django.utils.timezone
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='GuestSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(db_index=True, max_length=40, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('custom_id', models.CharField(editable=False, max_length=30, unique=True, verbose_name='ID Personalizado')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrador'), ('GESTOR', 'Gestor de la Base de Conocimiento'), ('REGISTRADO', 'Usuario Registrado')], default='REGISTRADO', max_length=20, verbose_name='Rol')),
                ('daily_message_limit', models.IntegerField(default=50, verbose_name='Límite de Mensajes Diarios')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Nueva Consulta Legal', max_length=255, verbose_name='Título de la Conversación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
                ('guest_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='core.guestsession')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('USER', 'Usuario'), ('ASSISTANT', 'Asistente IA'), ('SYSTEM', 'Sistema')], max_length=10, verbose_name='Emisor')),
                ('content', models.TextField(verbose_name='Mensaje')),
                ('is_out_of_scope', models.BooleanField(default=False, verbose_name='Fuera de Ámbito (Guardrail)')),
                ('llm_provider', models.CharField(blank=True, max_length=20, null=True, verbose_name='Proveedor LLM')),
                ('llm_model', models.CharField(blank=True, max_length=50, null=True, verbose_name='Modelo LLM')),
                ('tokens_used', models.IntegerField(blank=True, null=True, verbose_name='Tokens Consumidos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.chatsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FederalLaw',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('official_title', models.CharField(db_index=True, max_length=500, verbose_name='Título Oficial de la Ley')),
                ('short_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Siglas / Nombre Corto')),
                ('dof_publication_date', models.DateField(blank=True, null=True, verbose_name='Fecha Publicación DOF')),
                ('dof_last_reform_date', models.DateField(blank=True, null=True, verbose_name='Última Reforma DOF')),
                ('pdf_file', models.FileField(upload_to='laws_pdf/', verbose_name='Archivo PDF')),
                ('file_hash', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Hash SHA-256 PDF')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('EXTRACTING', 'Extrayendo Texto'), ('INDEXED', 'Indexado / Vectorizado'), ('FAILED', 'Error en Procesamiento')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Vigente en RAG')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_laws', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LawSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_type', models.CharField(choices=[('TITULO', 'Título'), ('CAPITULO', 'Capítulo'), ('ARTICULO', 'Artículo'), ('TRANSITORIO', 'Transitorio')], max_length=20, verbose_name='Tipo')),
                ('article_number', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Número de Artículo')),
                ('title', models.CharField(max_length=255, verbose_name='Título de la Sección')),
                ('raw_content', models.TextField(verbose_name='Texto Íntegro')),
                ('order', models.IntegerField(db_index=True, verbose_name='Orden Cronológico')),
                ('law', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.federallaw')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LawChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('article_reference', models.CharField(max_length=150, verbose_name='Referencia para Prompt')),
                ('content', models.TextField(verbose_name='Texto del Fragmento')),
                ('chunk_hash', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Hash SHA-256 Fragmento')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1024)),
                ('metadata', models.JSONField(default=dict, verbose_name='Metadatos Adicionales')),
                ('law', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='core.federallaw')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='core.lawsection')),
            ],
        ),
        migrations.CreateModel(
            name='MessageCitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('law_title', models.CharField(max_length=500, verbose_name='Título de Ley Citada')),
                ('article_reference', models.CharField(max_length=150, verbose_name='Artículo Citado')),
                ('relevance_score', models.FloatField(verbose_name='Similitud Semántica')),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citations', to='core.lawchunk')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='core.chatmessage')),
            ],
        ),
        migrations.CreateModel(
            name='UserUsageQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('messages_sent', models.IntegerField(default=0)),
                ('max_limit', models.IntegerField(default=50)),
                ('guest_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_quotas', to='core.guestsession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_quotas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='unique_user_daily_quota'), models.UniqueConstraint(fields=('guest_session', 'date'), name='unique_guest_daily_quota')],
            },
        ),
    ]
