# Generated by Django 5.2.17 on 2026-09-30 03:01

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('correo_electronico', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre(s)')),
                ('apellido', models.CharField(max_length=60, verbose_name='Apellidos')),
                ('rol', models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('GESTOR', 'Gestor de la Base de Conocimiento'), ('REGISTRADO', 'Usuario Registrado')], default='REGISTRADO', max_length=30, verbose_name='Rol')),
                ('cuota_diaria_mensajes', models.IntegerField(default=50, verbose_name='Cuota diaria de mensajes')),
                ('mensajes_usados_hoy', models.IntegerField(default=0, verbose_name='Mensajes usados hoy')),
                ('activo', models.BooleanField(default=True, verbose_name='Cuenta activa')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Es Staff')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(default='Consulta Normativa', max_length=200, verbose_name='Título de la conversación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de inicio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Conversación',
                'verbose_name_plural': 'Conversaciones',
                'db_table': 'conversacion',
            },
        ),
        migrations.CreateModel(
            name='LeyFederal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500, unique=True, verbose_name='Nombre oficial')),
                ('siglas', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Siglas/Abreviatura')),
                ('fecha_publicacion', models.DateField(verbose_name='Fecha de publicación')),
                ('fecha_ultima_reforma', models.DateField(verbose_name='Fecha de última reforma')),
                ('version_actual', models.IntegerField(default=1, verbose_name='Versión actual')),
                ('hash_documento', models.CharField(max_length=64, unique=True, verbose_name='Hash SHA-256 del documento')),
                ('estado', models.CharField(choices=[('VIGENTE', 'Vigente'), ('ABROGADA', 'Abrogada')], default='VIGENTE', max_length=20, verbose_name='Estado normativo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leyes_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Gestor')),
            ],
            options={
                'verbose_name': 'Ley Federal',
                'verbose_name_plural': 'Leyes Federales',
                'db_table': 'leyes_federales',
            },
        ),
        migrations.CreateModel(
            name='FragmentoNormativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido_fragmento', models.TextField(verbose_name='Contenido del fragmento')),
                ('vector_embedding', pgvector.django.vector.VectorField(dimensions=768, verbose_name='Vector Embedding (768 dims)')),
                ('hash_fragmento', models.CharField(max_length=64, unique=True, verbose_name='Hash SHA-256 del fragmento')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('ley', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragmentos', to='core.leyfederal', verbose_name='Ley asociada')),
            ],
            options={
                'verbose_name': 'Fragmento Normativo',
                'verbose_name_plural': 'Fragmentos Normativos',
                'db_table': 'fragmentos_normativos',
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emisor', models.CharField(choices=[('USUARIO', 'Usuario'), ('SISTEMA', 'Sistema')], max_length=20, verbose_name='Emisor')),
                ('contenido_texto', models.TextField(verbose_name='Contenido del mensaje')),
                ('proveedor_ia', models.CharField(blank=True, choices=[('GROQ', 'Groq Cloud'), ('GEMINI', 'Google Gemini')], max_length=20, null=True, verbose_name='Proveedor de IA seleccionado')),
                ('conmutado_fallback', models.BooleanField(default=False, verbose_name='¿Conmutado por Fallback?')),
                ('citas', models.JSONField(blank=True, null=True, verbose_name='Citas normativas')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envío')),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='core.conversacion', verbose_name='Conversación')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'db_table': 'mensajes',
            },
        ),
        migrations.CreateModel(
            name='RegistroFalloAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor_solicitado', models.CharField(choices=[('GROQ', 'Groq Cloud'), ('GEMINI', 'Google Gemini')], max_length=20, verbose_name='Proveedor solicitado')),
                ('codigo_error', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código de error / Excepción')),
                ('conmutado_a', models.CharField(blank=True, choices=[('GROQ', 'Groq Cloud'), ('GEMINI', 'Google Gemini')], max_length=20, null=True, verbose_name='Conmutado a (Respaldo)')),
                ('exitoso', models.BooleanField(default=False, verbose_name='¿Conmutación exitosa?')),
                ('fecha_evento', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del evento')),
                ('mensaje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fallos_api', to='core.mensaje', verbose_name='Mensaje asociado')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fallos_api', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de Fallo de API',
                'verbose_name_plural': 'Registros de Fallos de API',
                'db_table': 'registros_fallos_api',
            },
        ),
    ]
